name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
  - chore/full-pipeline

pool:
  vmImage: "windows-2019"

variables:
  buildConfiguration: "Release"
  system.debug: false
  buildNumber: 0.24.0-$(Rev:.r)

stages:
  - stage: Checks
    jobs:
      - job: "Check_for_changes"
        steps:
          - script: echo $(name)
          - checkout: self
            submodules: "recursive"
      - job: "Publish_nuget"
        steps:
          - checkout: self
            submodules: true

        - script: |
            cd core/web
            npm version $(buildNumber)
            npm install \
            npm run build

          - task: Npm@1
            displayName: "npm publish beta (refs/heads/beta)"
            inputs:
              command: custom
              verbose: false
              customCommand: "publish --tag beta"
              publishEndpoint: npm
              customEndpoint: npm
              workingDir: $(workingDir)
            continueOnError: true
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/chore/full-pipeline'))

          - task: Npm@1
            displayName: "npm publish release (refs/heads/master)"
            inputs:
              command: publish
              verbose: false
              publishEndpoint: npm
              customEndpoint: npm
              workingDir: $(workingDir)
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))

          - task: NuGetToolInstaller@1
            inputs:
              versionSpec: 6.0.100

          - task: DotNetCoreCLI@2
            displayName: "dotnet restore"
            inputs:
              command: "restore"

          - task: DotNetCoreCLI@2
            displayName: "dotnet pack"
            inputs:
              command: "pack"
              arguments: "-p:SymbolPackageFormat=snupkg"
              packagesToPack: "**/*.csproj"
              versioningScheme: "byBuildNumber"
              # versionEnvVar: buildNumber

          - script: "ls $(Build.ArtifactStagingDirectory)/*.nupkg"
            displayName: "ls"

          - script: 'dotnet nuget push $(Build.ArtifactStagingDirectory)\*.nupkg --api-key $(nuget_key) --source https://api.nuget.org/v3/index.json'
            displayName: "dotnet nuget push"
