//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Profile
{
	displayName: string|null;
	id: string|null;
	email: string|null;
	identityName: string|null;
	isAuthenticated: boolean;
}
export interface IConfigurationMeta
{
	route: string|null;
	title: string|null;
	id: string|null;
	sectionId: string|null;
}
