
/* this file is autogenerated. Do not edit. */

export interface Portfolio {
  id: string
  displayName: string | null
  files: PortfolioFile[]
}

export const defaultPortfolio: Portfolio = {
  id: "00000000-0000-0000-0000-000000000000",
  displayName: "",
  files: [],
}

export interface PortfolioFile {
  id: string
  name: string | null
  path: string | null
}

export const defaultPortfolioFile: PortfolioFile = {
  id: "00000000-0000-0000-0000-000000000000",
  name: "",
  path: "",
}

export interface IConfigurationMeta {
  route: string | null
  title: string | null
  id: string | null
  sectionId: string | null
}

export const defaultIConfigurationMeta: IConfigurationMeta = {
  route: "",
  title: "",
  id: "",
  sectionId: "",
}

export interface Profile {
  displayName: string | null
  id: string | null
  email: string | null
  identityName: string | null
  isAuthenticated: boolean
}

export const defaultProfile: Profile = {
  displayName: "",
  id: "",
  email: "",
  identityName: "",
  isAuthenticated: false,
}

export interface SampleConfiguration {
  prop1: string | null
  prop2: number
  nested: any
  enum: "EnumVal1" | "EnumVal2"
  nullableEnum: "EnumVal1" | "EnumVal2" | null
}

export const defaultSampleConfiguration: SampleConfiguration = {
  prop1: "",
  prop2: 0,
  nested: null as any,
  enum: "EnumVal1",
  nullableEnum: null,
}

export interface CreateUser {
  displayName: string | null
  email: string | null
}

export const defaultCreateUser: CreateUser = {
  displayName: "",
  email: "",
}

export interface CreatePortfolio {
  displayName: string | null
  files: any[]
}

export const defaultCreatePortfolio: CreatePortfolio = {
  displayName: "",
  files: [],
}

export interface DeletePortfolio {
  id: string
}

export const defaultDeletePortfolio: DeletePortfolio = {
  id: "00000000-0000-0000-0000-000000000000",
}

export interface Unit {
}

export const defaultUnit: Unit = {
}

export interface UpdatePortfolio {
  displayName: string | null
  id: string
  files: any[]
}

export const defaultUpdatePortfolio: UpdatePortfolio = {
  displayName: "",
  id: "00000000-0000-0000-0000-000000000000",
  files: [],
}

export declare module Entities {
  export type Portfolio = "Glow.Sample.Files.Portfolio"
  export type PortfolioFile = "Glow.Sample.Files.PortfolioFile"
  export type IConfigurationMeta = "Glow.Configurations.IConfigurationMeta"
  export type Profile = "Glow.Core.Profiles.Profile"
  export type SampleConfiguration = "Glow.Sample.Configurations.SampleConfiguration"
  export type CreateUser = "Glow.Sample.Forms.CreateUser"
  export type CreatePortfolio = "Glow.Sample.Files.CreatePortfolio"
  export type DeletePortfolio = "Glow.Sample.Files.DeletePortfolio"
  export type Unit = "MediatR.Unit"
  export type UpdatePortfolio = "Glow.Sample.Files.UpdatePortfolio"

  export type All = Portfolio | PortfolioFile | IConfigurationMeta | Profile | SampleConfiguration | CreateUser | CreatePortfolio | DeletePortfolio | Unit | UpdatePortfolio
}
