
/* this file is autogenerated. Do not edit. */

export interface Portfolio {
  id: string
  displayName: string | null
  files: PortfolioFile[]
}

export const defaultPortfolio: Portfolio = {
  id: "00000000-0000-0000-0000-000000000000",
  displayName: "",
  files: [],
}

export interface PortfolioFile {
  id: string
  name: string | null
  path: string | null
}

export const defaultPortfolioFile: PortfolioFile = {
  id: "00000000-0000-0000-0000-000000000000",
  name: "",
  path: "",
}

export interface IConfigurationMeta {
  route: string | null
  title: string | null
  id: string | null
  sectionId: string | null
}

export const defaultIConfigurationMeta: IConfigurationMeta = {
  route: "",
  title: "",
  id: "",
  sectionId: "",
}

export interface Profile {
  displayName: string | null
  id: string | null
  email: string | null
  identityName: string | null
  isAuthenticated: boolean
}

export const defaultProfile: Profile = {
  displayName: "",
  id: "",
  email: "",
  identityName: "",
  isAuthenticated: false,
}

export declare module Entities {
  export type Portfolio = "Glow.Sample.Files.Portfolio"
  export type PortfolioFile = "Glow.Sample.Files.PortfolioFile"
  export type IConfigurationMeta = "Glow.Configurations.IConfigurationMeta"
  export type Profile = "Glow.Core.Profiles.Profile"

  export type All = Portfolio | PortfolioFile | IConfigurationMeta | Profile
}
