name: react-antd-aspnetcore-app

trigger:
  - master
  - build-on-source-changes

pool:
  vmImage: "windows-latest"

jobs:
  - job: "Check_for_changes"
    steps:
      - checkout: self
        submodules: "recursive"
      - bash: |
          PATH_FILTER="templates/"
          CHANGED_FILES=$(git diff HEAD HEAD~ --name-only)
          MATCH_COUNT=0

          echo "Checking for file changes..."
          for FILE in $CHANGED_FILES
          do
            if [[ $FILE == *$PATH_FILTER* ]]; then
              echo "MATCH:  ${FILE} changed"
              MATCH_COUNT=$(($MATCH_COUNT+1))
            else
              echo "IGNORE: ${FILE} changed"
            fi
          done

          echo "$MATCH_COUNT match(es) for filter '$PATH_FILTER' found."
          if [[ $MATCH_COUNT -gt 0 ]]; then
            echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]true"
          else
            echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]false"
          fi
        name: check_changes
        displayName: "Check changed files"
  - job: Publish
    dependsOn: "Check_for_changes"
    condition: eq(dependencies.Check_for_changes.outputs['check_changes.SOURCE_CODE_CHANGED'], 'true') #map doThing and check the value
    steps:
      - checkout: self
        submodules: "recursive"
      - bash: echo $(check_changes.SOURCE_CODE_CHANGED)
      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: "5.2"
      - task: NuGetCommand@2
        displayName: "NuGet pack"
        inputs:
          command: pack
          packagesToPack: app/glow.app.nuspec
      - task: NuGetCommand@2
        displayName: "NuGet push"
        inputs:
          command: push
          nuGetFeedType: external
          publishFeedCredentials: nuget.org
