//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Profile {
  displayName: string | null
  identityName: string | null
  email: string | null
  objectId: string | null
  userId: string | null
  isAuthenticated: boolean
  scopes: string[]
  claims: any[]
}
