trigger:
- master
- release/*
- beta/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  workingDir: 'core/web'
steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
    workingDir: $(workingDir)

- task: Npm@1
  displayName: 'npm run test'
  continueOnError: true
  inputs:
    command: custom
    verbose: false
    customCommand: 'run test'
    workingDir: $(workingDir)

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'
    workingDir: $(workingDir)

- task: Npm@1
  displayName: 'npm publish beta (conditionally)'
  inputs:
    command: custom
    verbose: false
    customCommand: 'publish --tag beta'
    publishEndpoint: npm
    customEndpoint: npm
    workingDir: $(workingDir)
  continueOnError: true
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/beta'))

- task: Npm@1
  displayName: 'npm publish release (conditionally)'
  inputs:
    command: publish
    verbose: false
    publishEndpoint: npm
    customEndpoint: npm
    workingDir: $(workingDir)
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))
